src/main/java/com/sunbeaminfo/sh/onlinefood/beans/CartBean.java
package com.sunbeaminfo.sh.onlinefood.beans;

import java.util.ArrayList;
import java.util.List;

public class CartBean {
	private String[] itemIds;
	private List<Integer> cart;
	public CartBean() {
		this.itemIds = new String[0];
		this.cart = new ArrayList<Integer>();
	}
	public String[] getItemIds() {
		return itemIds;
	}
	public void setItemIds(String[] itemIds) {
		this.itemIds = itemIds;
	}
	public List<Integer> getCart() {
		return cart;
	}
	public void setCart(List<Integer> cart) {
		this.cart = cart;
	}
	public int getNewItemCount() {
		return this.itemIds.length;
	}
	public void addToCart() {
		for (String itemId : itemIds) {
			int id = Integer.parseInt(itemId);
			cart.add(id);
		}
	}
}

src/main/java/com/sunbeaminfo/sh/onlinefood/beans/ItemBean.java
package com.sunbeaminfo.sh.onlinefood.beans;

import java.util.ArrayList;
import java.util.List;

import com.sunbeaminfo.sh.onlinefood.daos.ItemDao;
import com.sunbeaminfo.sh.onlinefood.entities.Item;

public class ItemBean {
	private String category;
	private List<Item> items;
	public ItemBean() {
		this.category = "";
		this.items = new ArrayList<Item>();
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public List<Item> getItems() {
		return items;
	}
	public void setItems(List<Item> items) {
		this.items = items;
	}
	public void fetchItems() {
		try (ItemDao dao = new ItemDao()) {
			dao.open();
			this.items = dao.getItems(category);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

src/main/java/com/sunbeaminfo/sh/onlinefood/beans/LoginBean.java
package com.sunbeaminfo.sh.onlinefood.beans;

import com.sunbeaminfo.sh.onlinefood.daos.CustomerDao;
import com.sunbeaminfo.sh.onlinefood.entities.Customer;

public class LoginBean {
	private String email;
	private String password;
	private Customer customer;
	public LoginBean() {
		this.email = "";
		this.password = "";
		this.customer = null;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public Customer getCustomer() {
		return customer;
	}
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	public void authenticate() {
		try (CustomerDao dao = new CustomerDao()) {
			dao.open();
			Customer dbCust = dao.getCustomer(email);
			if(dbCust != null && password.equals(dbCust.getPassword()))
				this.customer = dbCust;
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

src/main/java/com/sunbeaminfo/sh/onlinefood/entities/Item.java
package com.sunbeaminfo.sh.onlinefood.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "ITEMS")
public class Item implements Serializable {
	@Id
	@Column
	private int id;
	@Column
	private String name;
	@Column
	private String category;
	@Column
	private String info;
	@Column
	private double price;
	public Item() {
		
	}
	public Item(int id, String name, String category, String info, double price) {
		this.id = id;
		this.name = name;
		this.category = category;
		this.info = info;
		this.price = price;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getInfo() {
		return info;
	}
	public void setInfo(String info) {
		this.info = info;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	@Override
	public String toString() {
		return "Item [id=" + id + ", name=" + name + ", category=" + category + ", info=" + info + ", price=" + price
				+ "]";
	}
}

src/main/webapp/WEB-INF/pages/addcart.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Add Cart</title>
</head>
<body>
	<jsp:useBean id="scb" class="com.sunbeaminfo.sh.onlinefood.beans.CartBean" scope="session"/>
	<jsp:setProperty name="scb" property="itemIds" param="item" />
	${scb.addToCart()}
	<jsp:forward page="/ctl?page=categories">
		<jsp:param name="message" value="${scb.newItemCount} New Items Added."/>
	</jsp:forward>
</body>
</html>

src/main/webapp/WEB-INF/pages/categories.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Categories</title>
</head>
<body>
	<jsp:useBean id="cb" class="com.sunbeaminfo.sh.onlinefood.beans.CategoryBean"/>
	
	${cb.fetchCategories()}
	
	<form method="post" action="ctl?page=items">
		<c:forEach var="cat" items="${cb.categories}">
			<input type="radio" name="category" value="${cat}"/> ${cat} <br/>
		</c:forEach>
		<input type="submit" value="Show Items"/>
		<a href="ctl?page=showcart">Show Cart</a>
	</form>
	<br/><br/>
	${param.message}. <br/>
	Number of items in cart ${scb.cart.size()}.
</body>
</html>

src/main/webapp/WEB-INF/pages/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Login</title>
</head>
<body>
	<form method="post" action="ctl?page=authenticate">
		Email: <input type="email" name="email"/> <br/>
		Password: <input type="password" name="password"/> <br/>
		<input type="submit" value="Sign In"/>
	</form>
</body>
</html>

src/main/webapp/WEB-INF/pages/items.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Items</title>
</head>
<body>
	<jsp:useBean id="ib" class="com.sunbeaminfo.sh.onlinefood.beans.ItemBean"/>
	<jsp:setProperty name="ib" property="*" />
	${ib.fetchItems()}
	
	<form method="post" action="ctl?page=addcart">
		<c:forEach var="i" items="${ib.items}">
			<input type="checkbox" name="item" value="${i.id}"/> ${i.name} <br/>
		</c:forEach>
		<input type="submit" value="Add Cart"/>
	</form>
</body>
</html>

src/main/webapp/WEB-INF/pages/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Authentication</title>
</head>
<body>
	<jsp:useBean id="lb" class="com.sunbeaminfo.sh.onlinefood.beans.LoginBean"/>
	<jsp:setProperty name="lb"  property="*" />
	${lb.authenticate()}
	<c:choose>
		<c:when test="${lb.customer != null}">
			<c:redirect url="ctl?page=categories"/>
		</c:when>
		<c:otherwise>
			Invalid email or password. <br/>
			<a href="ctl?page=index">Login Again</a>
		</c:otherwise>
	</c:choose>
</body>
</html>

src/main/webapp/WEB-INF/pages/logout.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Logout</title>
</head>
<body>
	Thank You. <br/>
	<% session.invalidate(); %>
	<a href="ctl?page=index">Login Again</a>
</body>
</html>

src/main/webapp/WEB-INF/pages/showcart.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Show Cart</title>
</head>
<body>
	Using Java Beans
	<jsp:useBean id="fb" class="com.sunbeaminfo.sh.onlinefood.beans.FoodBean"/>
	<c:set var="total" value="0.0"/>
	<table border="1">
		<thead style="background-color: gray;">
			<tr>
				<td>Id</td>
				<td>Item</td>
				<td>Category</td>
				<td>Price</td>
			</tr>
		</thead>
	<c:forEach var="id" items="${scb.cart}">
		<jsp:setProperty name="fb" property="id" value="${id}"/>
		${fb.fetchItem()}
		<c:set var="total" value="${total + fb.item.price}"/>
		<tr>
			<td>${id}</td>
			<td>${fb.item.name}</td>
			<td>${fb.item.category}</td>
			<td>${fb.item.price}</td>
		</tr>
	</c:forEach>
	</table>	
	<br/><br/>
	Total Bill: Rs. ${total}/-
	<br/><br/>
	<a href="ctl?page=logout">Sign Out</a>
</body>
</html>

src/main/webapp/WEB-INF/pages/showcart2.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="shop" uri="/WEB-INF/shop.tld" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Show Cart2</title>
</head>
<body>
	Using Custom Tags
	<c:set var="total" value="0.0"/>
	<table border="1">
		<thead style="background-color: gray;">
			<tr>
				<td>Id</td>
				<td>Item</td>
				<td>Category</td>
				<td>Price</td>
			</tr>
		</thead>
	<c:forEach var="id" items="${scb.cart}">
		<shop:food id="${id}"/>
	</c:forEach>
	</table>	
	<br/><br/>
	Total Bill: Rs. ${total}/-
	<br/><br/>
	<a href="ctl?page=logout">Sign Out</a>
</body>
</html>